server:
  port: 3000
spring:
  application:
    name: tmall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 10.38.167.199:80

    alicloud:
      access-key: LTAI4G2FLaijpsLoJ8JyGAcy
      secret-key: nx8rnaFpOprp56BrMxn4xyZO4GyLwq
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: wttoss